export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CHANGE_SERVICE = 'CHANGE_SERVICE';
export const CHANGE_SERVICE_CANCEL = 'CHANGE_SERVICE_CANCEL';
export const FILTR_SERVICE_FIELD = 'FILTR_SERVICE_FIELD';